### ISSUE TITLE
Dev Server

### ISSUE THREAD

**Issue by squidkid1** [DylanPina/RUCS-Hub#4]
I'm not sure if this issue was on my end or something with the dev server. But clicking profile, after logging in, causes: TypeError: Cannot read properties of undefined (reading 'getTime'). And trying to upvote causes: Error:  Invalid `prisma.vote.create()` invocation: Foreign key constraint failed on the field: `Vote_userId_fkey (index)`.  I did notice that new logins weren't being updated for 'User" in the database because the last time a user was added was may 19. This may be a local issue but I'm not sure. It would be appreciated if anyone could try to run development server and see if it works on their end.

**Comment by DylanPina** [comment]
Looking into this issue now. Thank you for your feedback.

**Comment by DylanPina** [comment]
I believe I have resolved this issue. The issue was regarding lack of permissions with the auth0 management API, which resulted in users not being added to the database after registration. 

When accessing certain pages, the client attempts to fetch the user (which doesn't exist) from the database and then promptly throws errors. 

Pull the latest changes from the `dev` branch and let me know if any issues persist or arise.

Thank you for your feedback and support.

**Comment by DylanPina** [comment]
Note that you will have to logout of any previous sessions and re-register your account
